export const ADD_PHOTOS = 'ADD_PHOTOS';
export const REQUEST_PREVIEW = 'REQUEST_PREVIEW';
export const RECEIVE_PREVIEW = 'RECEIVE_PREVIEW';
export const NEXT_PHOTO = 'NEXT_PHOTO';
export const PREVIOUS_PHOTO = 'PREVIOUS_PHOTO';
export const SHOW_PHOTO = 'SHOW_PHOTO';
export const SHOW_THUMBNAILS = 'SHOW_THUMBNAILS';
export const SET_PHOTOS = 'SET_PHOTOS';
